apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: fd-ambulance-ufe-content
spec:
  microFrontend: fd-ambulance-ufe
  element: fd-ambulance-wl-app
  attributes:
    - name: base-path
      value: /fd-ambulance-wl/
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: kornot
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?fd-ambulance-wl(/.*)?$"